baseURL = "http://hugo.copt.io"
languageCode = "en-us"
title = "Copt"
enableRobotsTXT = true
theme = "agen-hugo"

[params]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
