backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
  local_backend: true
media_folder: static/img
public_folder: /img
collections:
<<<<<<< HEAD
  - name: "services"
    label: "services"
    description: "services"
    files:
      - label: "services"
        name: "services"
        file: "data/service.yml"
        fields:
          - label: "services"
            name: "services"
            widget: "list"
            fields:
              - {label: "title", name: "title", widget: "string"}
              - {label: "icon", name: "icon", widget: "string"}
              - {label: "content", name: "content", widget: "string"}
=======
  - name: sellers
    label: sellers
    files:
      - name: sellers
        label: Sellers
        file: data/sellers.yml
        fields:
          - widget: string
            name: title
            label: title
            required: true
          - widget: string
            name: image_url
            label: image
            required: true
>>>>>>> ba32600 (New changes for sellers)
