backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
  local_backend: true
media_folder: static/img
public_folder: /img
collections:
  - name: "sellers"
    label: "sellers"
    description: "sellers"
    files:
      - label: "sellers"
        name: "sellers"
        file: "data/seller.yml"
        fields:
          - label: "sellers"
            name: "sellers"
            widget: "list"
            fields:
              - {label: "title", name: "title", widget: "string"}
              - {label: "image_url", name: "image_url", widget: "string"}
            
