backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
  local_backend: true
media_folder: static/img
public_folder: /img
collections:
  - name: sellers
    label: sellers
    files:
      - name: sellers
        label: Sellers
        file: data/seller.yml
        fields:
          - widget: string
            name: title
            label: title
            required: true
          - widget: string
            name: image_url
            label: image
            required: true
