backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: static/img
public_folder: /img
collections:
  - name: services
    label: services
    files:
      - name: services
        label: Services
        file: data/service.yml
        fields:
          - widget: string
            name: title
            label: title
            required: true
          - widget: string
            name: icon
            label: icon
            required: true
          - widget: string
            name: content
            label: content
            required: true
