backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
  local_backend: true
media_folder: static/img
public_folder: /img
collections:
  - name: "services"
    label: "services"
    description: "services"
    files:
      - label: "services"
        name: "services"
        file: "data/service.yml"
        fields:
          - label: "services"
            name: "services"
            widget: "list"
            fields:
              - {label: "title", name: "title", widget: "string"}
              - {label: "icon", name: "icon", widget: "string"}
              - {label: "content", name: "content", widget: "string"}
